#ifndef	__COMPILER_BACKEND_ASMGEN_H__
#define	__COMPILER_BACKEND_ASMGEN_H__

#define	BE_ASMGEN_PLATFORM_WINDOWS		1
#define	BE_ASMGEN_PLATFORM_SYSTEM_V		2
#define	BE_ASMGEN_PLATFORM_ISYSTEM		3
#define	BE_ASMGEN_PLATFORM_DEFAULT		BE_ASMGEN_PLATFORM_ISYSTEM

#endif
